"""initial migration

Revision ID: 1b9bc83db33a
Revises: 
Create Date: 2020-06-25 01:54:42.521780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b9bc83db33a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('tee_yardage', sa.Integer(), nullable=True),
    sa.Column('course_rating', sa.Float(), nullable=True),
    sa.Column('slope_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('tee_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('score_by_hole', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('putts', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('fairways', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('gir', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['tee_id'], ['tees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yardages',
    sa.Column('tee_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('yardage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.id'], ),
    sa.ForeignKeyConstraint(['tee_id'], ['tees.id'], ),
    sa.PrimaryKeyConstraint('tee_id', 'hole_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yardages')
    op.drop_table('rounds')
    op.drop_table('tees')
    op.drop_table('holes')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
